/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ahadas' at '8/1/16 9:51 PM' with Gradle 2.14
 *
 * @author ahadas, @date 8/1/16 9:51 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
